deploymentDiagram
    title Diagrama de Despliegue

    node "Servidor UM" {
        artifact "mercadopago-service.jar" {
            component "Spring Boot App"
        }
        database "Base de Datos (Externa)" as DB {
            component "Datos de Tesorería"
        }
    }

    node "Plataforma Mercado Pago" {
        component "API de Mercado Pago" as MP_API
    }

    "Spring Boot App" -->> MP_API : "HTTPS/REST"
    "Spring Boot App" -->> DB : "JDBC"