deploymentDiagram
    title Diagrama de Despliegue

    node "Servidor UM" {
        artifact "mercadopago-service.jar" {
            component "Spring Boot 4.1 App"
        }
    }

    node "Backend Tesorería Core" {
        component "tesoreria-core-service" as CORE
    }

    node "Plataforma Mercado Pago" {
        component "API de Mercado Pago" as MP_API
    }

    "Spring Boot 4.1 App" -->> MP_API : "HTTPS/REST"
    "Spring Boot 4.1 App" -->> CORE : "Feign Client / HTTP"